# Generated by Django 4.2.24 on 2025-10-09 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gramapp', '0002_alter_member_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('designation', models.TextField()),
                ('contact', models.BigIntegerField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='post_images/')),
            ],
        ),
    ]
